# Generated by Django 6.0.3 on 2026-03-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_announcement_course_courseplan_exam_financerecord_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectmark',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subjectmark',
            name='cie_marks',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='subjectmark',
            name='course_code',
            field=models.CharField(default='CODE', max_length=20),
        ),
        migrations.AddField(
            model_name='subjectmark',
            name='credits_registered',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='subjectmark',
            name='see_marks',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='subjectmark',
            name='subject_name',
            field=models.CharField(max_length=150),
        ),
        migrations.RemoveField(
            model_name='subjectmark',
            name='marks_obtained',
        ),
        migrations.RemoveField(
            model_name='subjectmark',
            name='max_marks',
        ),
    ]
