# Generated by Django 6.0.3 on 2026-04-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_student_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmark',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
